### ISSUE TITLE
Commands to add

### ISSUE THREAD

**Issue by tonibm19** [cuberite/Essentials#22]
I'll write here of a list with the commands I plan to add as for now:
/afk

If you want some other command in specific comment here.

**Comment by NiLSPACE** [comment]
Shouldn't be too hard. Just cWorld:ForEach all the players, and check the distance. You could even make it use a single command handler
```lua
local Distance = (a_Split[1] == "/shout") and 128 or 16
```

**Comment by tonibm19** [comment]
Added /shout and /whisper

**Comment by mathias-github** [comment]
/whisper is an alias of /msg in Bukkit's Essentials, so that can be a bit confusing for new players.

**Comment by tonibm19** [comment]
damn D:
I prefeare to use /whisper as its now
What about other people? what do you think? Try to be as closest posible to bukkit?

**Comment by mathias-github** [comment]
I didn't realize /shout and /whisper were different commands at first. /murmur could be an alternative to /whisper, but I think /whisper sounds the best.

**Comment by mathias-github** [comment]
Any chance you could look at implementing a /powertool command? Players keep asking for it. :P

**Comment by tonibm19** [comment]
Ill have a look.
The problem I see is how to save the command to the item.
