### ISSUE TITLE
Move repository over to cuberite organization

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/Essentials#44]

**Comment by SphinxC0re** [comment]
Bump!

**Comment by tonibm19** [comment]
Lua!

**Comment by tonibm19** [comment]
Its just that it reminded me the library I used for a lua project :P
https://github.com/kikito/bump.lua

**Comment by SphinxC0re** [comment]
@madmaxoft could you please move this repository?

**Comment by SphinxC0re** [comment]
Thanks :smile:
