### ISSUE TITLE
Game Mode being changed by warping

### ISSUE THREAD

**Issue by Fighter19** [cuberite/Essentials#52]
When using the warp command the player's gamemode is being set to the default for the world.
However this also applies to people which do not have the default gamemode and try to warp inside a world.

**Comment by tonibm19** [comment]
just set, in config.lua:
change_gm_when_changing_world = true
to

change_gm_when_changing_world = false

**Comment by tonibm19** [comment]
It should be working fine now. Before it changed gamemode even when warping into the same world, now only if changing world.
