### ISSUE TITLE
Some ranged monsters will fire immediately upon being spawned with /mob

### ISSUE THREAD

**Issue by mathwhiz1212** [cuberite/Essentials#54]
Skeleton will fire immediately on being spawned

Blaze will fire immediately as well but in a random direction. I was in a forest.... I lost 3 trees (Stumps remaining) and the 4th was fire scarred it would likely have been worse if I hadn't tried to put it out.

**Comment by tonibm19** [comment]
Well, if its day skeletons will burn.
Its a normal vanilla behaviour

**Comment by SphinxC0re** [comment]
I think he means that the Skeleton were firing at him ;-)

**Comment by LogicParrot** [comment]
If it's about skeletons shooting too soon, then this belongs to Cuberite's codebase, and not the Essentials plugin. I wonder why blazes fire in a random direction. A position read from an invalid pointer D: ?

**Comment by tonibm19** [comment]
Aw, sorry.
It has to do witj Cuberite then, I suppose.

**Comment by mathwhiz1212** [comment]
I need to test and see if behavior is different from when they spawn naturally and when I spawn them with /mob

**Comment by LogicParrot** [comment]
It is most likely the same behavior.
