### ISSUE TITLE
[Feature] Config Option for disabling Baby Wither

### ISSUE THREAD

**Issue by quixQuery** [cuberite/Essentials#67]
The baby wither is finicky. You never know when placing one of the heads to spawn the wither boss is going to spawn a baby wither, or, even if you do get all the wither skulls in place for a normal wither, sometimes nothing spawns.

Would appreciate a config option to disable baby wither spawning, or maybe a better in-world recipe so it doesn't conflict with the traditional wither.

Thanks! Just a suggestion, no need to implement.

**Comment by mathiascode** [comment]
Not sure what you mean with baby wither.
